[{if $oxcmp_user && $oxcmp_user->oxuser__oxrights->value == "malladmin" && $smarty.cookies.scsspreview}]
    [{oxstyle include="css/preview.css?"|cat:$smarty.now}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]